### ISSUE TITLE
Alarm functions not defined for DS3232RTC

### ISSUE THREAD

**Issue by nathantgray** [GuruSR/SmallRTC#1]
Looks like the alarm functionality for DS3232RTC is not defined. At the moment this is too over my head to fix myself. I thought it might be worth listing here.
.pio/libdeps/esp32dev/SmallRTC/SmallRTC.cpp:170:16: error: 'class DS3232RTC' has no member named 'clearAlarm'

**Comment by GuruSR** [comment]
Not sure where you're getting the DS3232RTC, but the one being used by the Watchy has had it from the beginning:

https://github.com/JChristensen/DS3232RTC

That one is the one being used.

**Comment by GuruSR** [comment]
To compile this or any Watchy code, you need the base Watchy libraries, those include the DS3232RTC and the PCF8563 among others.

**Comment by nathantgray** [comment]
For clarity, I encountered this error while trying to compile Watchy_GSR.
After revisiting this I think I understand it a bit better. The problem is that SmallRTC thinks that DS3232RTC has a clearAlarm method. However, DS3232RTC does not define that method. The original WatchyRTC (which I believe was replaced by SmallRTC) defined clearAlarm itself rather than calling it from DS3232RTC.

**Comment by GuruSR** [comment]
> For clarity, I encountered this error while trying to compile Watchy_GSR. After revisiting this I think I understand it a bit better. The problem is that SmallRTC thinks that DS3232RTC has a clearAlarm method. However, DS3232RTC does not define that method. The original WatchyRTC (which I believe was replaced by SmallRTC) defined clearAlarm itself rather than calling it from DS3232RTC.

The DS3232RTC I gave you in the link *does* have a clearAlarm in it, that is the one you're supposed to be using with the Watchy base libraries.  Revisit the Compilation Instructions and see what library sets you're needing, as you are missing crucial libraries if you're getting an error of a DS3232RTC library that is 2+ years old.

**Comment by nathantgray** [comment]
You are right. For some reason the library I am using is not the newest version. The Watchy version is 1.4.0 but the DS3232RTC version is 1.2.12 while the newest version is 2.0.0. I am using PlatformIO to automatically manage library dependencies. For some reason it did not clone the most recent version of DS3232RTC. I will have to figure out why that is happening and what else is also old. Thanks for your advice. I will close this issue.
